### ISSUE TITLE
The problem with the application iOS.

### ISSUE THREAD

**Issue by Kostya989** [voroshkov/Chorus-RF-Laptimer#101]
I did not find how to contact the author of the application.
There are problems connecting via Wi-Fi. The connection is unstable, it seems that the smartphone is falling asleep and the connection is broken.
And in case of a successful connection, a message appears.
![IMG_E9572](https://user-images.githubusercontent.com/48642964/54487561-1ffaad00-48a0-11e9-8c76-a2edf9ac759e.JPG)
![IMG_E9573](https://user-images.githubusercontent.com/48642964/54487562-1ffaad00-48a0-11e9-969f-f1e2d804d038.JPG)
Tested on
iPhone 7 iOS 12.1.4
iPad 10.5 iOS 12.1.4

**Comment by voroshkov** [comment]
Please check in the Facebook group. If I remember correctly Lazar Djordjevic mentioned that new version of iOS app is going to be released soon. Meanwhile you may change the API Version in Arduino code to 4 to have your app working

**Comment by Kostya989** [comment]
Ok, thanks. I will try to figure out where to change the API.
