### ISSUE TITLE
Store Channel, Pilot Name, and RSSI settings of each device between sessions

### ISSUE THREAD

**Issue by highway11** [voroshkov/Chorus-RF-Laptimer#11]
A nice feature would be if the system could remember the last used settings for each device:
 
1. Channel/Band selection
2. Pilot name
3. RSSI Threshold. (this one may be debatable, as this might be better to set every time?) 

Also (but less important) store these preferences: Enable Sounds, Enable Speech, Laps To Go, Min Lap Time

For example, at our weekly meetups, we always use the same 5 channels, (IMD5) and often even the same Pilots so it would be nice to be able to turn on the Chorus and the app automatically sets them all to the last used settings. This would make setup time very fast.

**Comment by traced** [comment]
I think these values could be easily stored into the eprom?!
