### ISSUE TITLE
RSSI not shown on last device

### ISSUE THREAD

**Issue by FranzAr** [voroshkov/Chorus-RF-Laptimer#12]
Have 4 devices, on the Pilots tab the last device RSSI shows "1". If I do "Set" it works correctly. Laps are also triggered correctly.

![screenshot_20170322-191731](https://cloud.githubusercontent.com/assets/10727513/24239292/b6056246-0fad-11e7-8d7e-156272310867.png)

![screenshot_20170322-191715](https://cloud.githubusercontent.com/assets/10727513/24239363/f30d7df4-0fad-11e7-926a-3e3dbf933d83.png)

**Comment by voroshkov** [comment]
Did you update the Android app and Arduino firmware since last weekend?
Is the issue persistent? Does it work this way right after connection and after disconnect/connect cycle?

**Comment by FranzAr** [comment]
Yes, both latest version

**Comment by voroshkov** [comment]
Do you have the problem with 4 devices only? Can you describe the use case?

**Comment by FranzAr** [comment]
Yes, had no problems like that with only 2 devices. Was just testing on the bench, but I could reproduce this behaviour every time. Gonna do some more investigation, when I have the time. On the Freq Tab it shows the right value, it's only on the Pilots tab. Just a small issue but wanted to let you know.

**Comment by voroshkov** [comment]
Got it. Thanks. Will take a look.

**Comment by voroshkov** [comment]
I guess I've found the reason of the described issue.
@FranzAr, can you try the updated APK from attached archive and let me know if it fixes the problem?

[ChorusRFLaptimer-release.zip](https://github.com/voroshkov/Chorus-RF-Laptimer/files/867188/ChorusRFLaptimer-release.zip)

**Comment by FranzAr** [comment]
Great, I'll try it tonight

**Comment by FranzAr** [comment]
Yes, problem seems to be solved, I get plausible values now on all 4 devices.

**Comment by voroshkov** [comment]
Cool. Will include the fix into next release then.
