### ISSUE TITLE
hey man , i am impressed.

### ISSUE THREAD

**Issue by gc9n** [voroshkov/Chorus-RF-Laptimer#15]
Hi there !
Congratulations for this Project! i am impressed.!!!
i made my self a firmware mixed for Realacc RX5808 Diversity Moduel Fatsharks , i added some OSD also .
I wanted to ask you something if you know , i want to implement "a fine tuning" method . or even free channel search , 
What i am saying is that i want to search throught the channels
from  5865 way to 5917
with step ++ 5865 , 5866, 5867 ....

i know that the channels goes through SPI registers like
 0x2906,    0x2910,    0x291A,    0x2984,    0x298E,    0x2998,    0x2A02,    0x2A0C,    // Band F / Airwave

What i dont know is how to pass through for example  5866  (not exists to the table of channels)  spi register !! so the problem is how to find the register for the right channel

**Comment by voroshkov** [comment]
You need to read docs for the chip used in RX5808. It's all there.
