### ISSUE TITLE
Help with Arduino Nano

### ISSUE THREAD

**Issue by androidiano78** [voroshkov/Chorus-RF-Laptimer#20]
Hi,
I just finished assembling a Solo device, but with Arduino Nano (not having Arduino Pro Mini). For now I have missed the part for voltage Lipo monitoring. That said, everything connects to the application via the bluetooth module, but I did not understand, the FREQ android app page, what is that number next to Device # 1, in my case 234. Going to the PILOTS page, RSSI Threshold gives me Always 1, and until I insert the above mentioned number (234), but it does not give me the option to set it, START RACE (1PILOT) does not appear on the RACE page. Once START RACE starts and I try to make a ride with the quadcopter (walking naturally for now, both with powered and non armed motors, but I do not think it makes any difference) when I step in front of the device nothing happens and does not ring buzzer. I would need help to figure out what the problem is, especially with wiring, since I am using Arduino Nano, but it should be compatible. I have only one device, so I did not connect the 4 pins to series more devices; In addition I did not even have the bridge to shorten two pins of Bluetooth (loopback jumper in scheme), I seemed to understand that it was to do for multiple connected devices.

My PinOut and configuration:

I supply everything from lipo - bec USB to mini USB - Arduino nano;
Ch1-Ch2-Ch3 (RX5808) - 1k resistors - D12-D11-D10 (Arduino nano);
GND (RX5808) - GND (HC-06 Module) - one of the 2 GNDs (Arduino nano);
+ 5v (RX5808) - 5V (Arduino nano) - VCC (HC-06 Module);
RSSI (RX5808) - A6 (Arduino nano);
Positive (Buzzer) - D6 (Arduino nano);
GND (Buzzer) - one of the 2 GNDs (Arduino nano);
RX0 (Arduino nano) - TXD (HC-06 Module);
TX1 (Arduino nano) - RXD (HC-06 Module).

I attach some photos and thank you in advance.
![setup](https://cloud.githubusercontent.com/assets/15347511/25772865/12f7d0d6-3274-11e7-9cde-f26344b7dfc1.jpg)
![freq](https://cloud.githubusercontent.com/assets/15347511/25772866/17b4699a-3274-11e7-9b5b-113f8a92187f.jpg)
![pilots](https://cloud.githubusercontent.com/assets/15347511/25772868/1b46cb52-3274-11e7-838b-6dd7f825e394.jpg)
![race](https://cloud.githubusercontent.com/assets/15347511/25772870/1e236b6e-3274-11e7-991e-6ac600042c95.jpg)
![solo device](https://cloud.githubusercontent.com/assets/15347511/25772874/2082c1d4-3274-11e7-80ed-efcf603e11f2.jpg)

**Comment by voroshkov** [comment]
Why do you connect RSSI to A6?

**Comment by androidiano78** [comment]
Oh my god, I apologize for the lapse and for the time that I made you lose .... I put the pinout, which among other things I was wrong also the CH, and now magically everything works. Now I have to test it only in flight. Congratulations on the work done

**Comment by voroshkov** [comment]
Good to have it solved! :)
