### ISSUE TITLE
Built with 5 SOLO issue

### ISSUE THREAD

**Issue by vannoz** [voroshkov/Chorus-RF-Laptimer#22]
Hello, I built a Chorus version with 5 SOLO. I have an issue when selecting players: name of 5th and 1st are the same and 5th SET rssi value doesn't change from 0, rtx receive the signal, but button SET doesn t work..only strange bip...any idea?
(Wirimg is ok, Uno pro are all ok...)
thanks

**Comment by voroshkov** [comment]
Can you make sure you use the latest app? Does it have LiPo monitor adjustment feature?
If yes, then please specify what Android device you are using.

**Comment by voroshkov** [comment]
Is Freq tab entirely visible on the screen or the 5th item is off?

**Comment by vannoz** [comment]
Hello Andrey, here you can see a video from my mobile:
https://youtu.be/iBP88XJ0LvI
Thanks
Ciao
Andrea

Il 31/mag/2017 16:29, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by voroshkov** [comment]
Thanks for the vid. I'll try to investigate what's happening. Looks like incorrect handling of  lists in android app. I'd appreciate if experienced Android devs could join and help here.

**Comment by vannoz** [comment]
Yes...unfortunately i'm olny Android user :)
maybe depends on the software you have used to build the Android app...I
tried the MIT App Inventor...but is not easy

Il 01/giu/2017 10:53, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by maddust** [comment]
I'm having the same problem . Any update with this issue?

**Comment by vannoz** [comment]
I think nothing up to now...Andrey is working to solve

Il 21/giu/2017 21:31, "maddust" <notifications@github.com> ha scritto:

**Comment by voroshkov** [comment]
Does anybody experience the same issue having different number of nodes? 4, or 6?

**Comment by vannoz** [comment]
With 4 units no problems...i don't have a 6th unit to do the test sorry

Il 22/giu/2017 08:40, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by vannoz** [comment]
ciao Andrey, I have some suggestios.
I tested this Sunday the laptimer chorus RF...mine is 5 unit...but if you
remember only 5 are working on the android app...
I used with 4 racers per time...we selected only 4 VTX frequencies...and
all the time I was changing the pilot name...then loosing a lot of time
My request is> is it possible to add a page where to list all players name,
then when preparing the partecipants to a race, select the names of the
participants from a drop down menu?
it will be also a good things to assign a COLOR code to some frequency...
it will be also a good things to see the MHz freq value per each
channel/band...because some time the VTX on the quad has not the same table
MHz vs channel/band...

thanks
ciao
Andrea

**Comment by voroshkov** [comment]
@vannoz valid points, but out of scope of this bug. Would you create a feature request(s) instead?

**Comment by highway11** [comment]
I'm also experiencing this bug. I recently added 2 more modules to upgrade from a 4 unit to 6 unit device. In the Pilots tab any changes I make to the 6th module get mirrored to the first one. I also cannot disable the 6th module to continue with 5 as the checkbox does not seem to work on the 6th as well

**Comment by vannoz** [comment]
Thanks. So I just have to install the new version?

Il 04/lug/2017 22:17, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by vannoz** [comment]
have you seen this?
https://www.banggood.com/LANTIAN-5_8G-Wide-Voltage-Bluetooth-Timer-Personal-Practice-Version-for-FPV-Racing-Drone-p-1237993.html?rmmds=search&cur_warehouse=CN

**Comment by voroshkov** [comment]
Yep. Already discussed in FB group :)

**Comment by vannoz** [comment]
Ah ok...sorry :)

Il 14/dic/2017 12:46, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by voroshkov** [comment]
Oh, you really shouldn't be! Thanks for notifying anyway!

**Comment by vannoz** [comment]
You did a great job...so I was scared seen others gain money with your idea!

Il 14/dic/2017 12:50, "Andrey Voroshkov" <notifications@github.com> ha
scritto:

**Comment by voroshkov** [comment]
If I could make huge money of it I'd try to :) So far I'm happy as it gains popularity as long as the license permits :)
