### ISSUE TITLE
Use analog edge triggering instead of trigger value

### ISSUE THREAD

**Issue by StarrrLiteNL** [voroshkov/Chorus-RF-Laptimer#24]
I think the reliability and precision of the timing system can be improved by using analog edge triggering instead of a simple trigger value. Eg: https://zone.ni.com/reference/en-XX/help/370466AC-01/mxcncpts/analogtriggering/

This would improve the reliability and precision of the system.

**Comment by voroshkov** [comment]
Probably it's true, but I'm not sure it's worth the efforts.
I think before trying this we need do define a method of measuring success/fail of the chosen approach.
