### ISSUE TITLE
8in1 PCB Version 2 

### ISSUE THREAD

**Issue by ps915** [voroshkov/Chorus-RF-Laptimer#28]
OK guys,

a while ago, i created a 8in1 PCB for the Chorus Tracker. It was my first design and of course the PCB was not 100% correct. There were some GND Pins of the Arduino not connected together "GND Island Fail". 

Now i came up with the Idea to create a stackable design. 

So there will be a 10x10 PCB with all the RX5808 receiver on top. You can either direct solder them or stackable with Pin Headers.

A second PCB, the Main PCB will be connected also with pin headers. 

I will create a second Main PCB for the Delta 5 Tracker as well. So one can choose if he wants to build delta5 or chorus.... or even another tracker.

All Arduinos from the PCB before can be used for this PCB as well. 2 pin headers were added becaus i included a buzzer which is shared with all 8 nodes via some schottky diodes. 

There is also an option to mount two XT30 connectors to the PCB and also a stepdown (Pololu 5V, 2.5A Step-Down D24V25F5) to power the whole unit via a LiPo. Second option is to power the unit via a external 5V source (powerbank)

Why two XT30? If the battery will run out of power, just connect a fresh one and charge the old one. 

An other feature is the Rj45 jack where you can plug in a network cable to extend the range of your bluethooth.

What is your opinion? Whats missing? 

<img width="1164" alt="1" src="https://user-images.githubusercontent.com/3420935/27518905-4b74b6c0-59ea-11e7-84ba-505252e45ec9.PNG">
<img width="682" alt="2" src="https://user-images.githubusercontent.com/3420935/27518906-4b8ad428-59ea-11e7-91f3-3b2852ba22cc.PNG">
<img width="1059" alt="3" src="https://user-images.githubusercontent.com/3420935/27518907-4b96208a-59ea-11e7-88b4-4a1c2e73c52f.PNG">
<img width="908" alt="4" src="https://user-images.githubusercontent.com/3420935/27518908-4b99453a-59ea-11e7-8781-16695f15ddc7.PNG">
<img width="919" alt="5" src="https://user-images.githubusercontent.com/3420935/27518909-4b9b2f30-59ea-11e7-9cbe-f55fc5be835d.PNG">
<img width="945" alt="7" src="https://user-images.githubusercontent.com/3420935/27518981-c16499ee-59eb-11e7-9da9-64137c8d4686.PNG">

<img width="1727" alt="6" src="https://user-images.githubusercontent.com/3420935/27519417-0188305a-59f4-11e7-88ce-b025d849d71b.PNG">

**Comment by Rikbruggink** [comment]
It looks really great Phillip!. Are you gonna release the pcb's to seedstudio or osh?

**Comment by ps915** [comment]
sure, they will be released on Seeedstudio when the testing is done and everything is fine

**Comment by ps915** [comment]
Update: Just decided to go with 8in1 PCB, no stackable RX PCB :-P

Ok guys. I spend a few weeks designing Chorus 8in1 V2 which should be the final version.
Features: 
- 10x10 PCB
- up 8 Nodes (if you use 6 nodes, just bridge TX/RX)
- 1 shared buzzer for all nodes (protected by diodes)
- 2x XT60 Input
- 2x MicroUSB 6V Input (Adafruit MicroUSB Breakout Board)
- 1x Serial Output RJ45 Socket
- 2x Serial Output Pin-Header
- 5V Stepdown ready (MP1584EN)
- all parts stackable (parts can be replaced easily, also better airflow, less heat)

As always, i will test it before publishing, but i think i wont find any issues this time =)
After that, you can order it yourself on seeedstudio.com
<img width="900" alt="1" src="https://user-images.githubusercontent.com/3420935/28009856-401213e4-655d-11e7-82c0-656c4b20ce5f.PNG">
<img width="869" alt="2" src="https://user-images.githubusercontent.com/3420935/28009855-400fd39a-655d-11e7-95a6-6908da175483.PNG">
<img width="979" alt="3" src="https://user-images.githubusercontent.com/3420935/28009857-40158358-655d-11e7-8d49-98bb825797fe.PNG">
<img width="1081" alt="4" src="https://user-images.githubusercontent.com/3420935/28009858-4016b32c-655d-11e7-96b1-91248d4b1c30.PNG">
<img width="881" alt="5" src="https://user-images.githubusercontent.com/3420935/28009860-401ed192-655d-11e7-8c20-73d81488066a.PNG">
<img width="831" alt="6" src="https://user-images.githubusercontent.com/3420935/28009859-401b34a6-655d-11e7-93ab-23f550e771a6.PNG">

**Comment by cbnlnk121** [comment]
@ps915 Maybe I'm missing it, but what's up with the dual XT60? I assume is runs right to the 5V stepdown first? Sorry for the newb question, just having a hard seeing the trace.

**Comment by cbnlnk121** [comment]
Deleted my prior comment ... Re-reviewing the trace, it's dual inputs. Great idea! Thanks!

**Comment by Chewpasta** [comment]
hi, i have a cuestion in this project, do you have a pcb with only 4 nodes?  ty!

**Comment by ps915** [comment]
I wont release the 8in1. Instead i nearly finished the 4in1. Stay tuned!
