### ISSUE TITLE
[Feature Request] Android app > Use speech API to say last\best times

### ISSUE THREAD

**Issue by TJohn7002** [voroshkov/Chorus-RF-Laptimer#4]
I think it will be great to hear last lap time once app got it from Chorus device.
Also it will be useful to hear best lap time right after last lap time.
smth like "Last lap: 23.6 sec... Best lap: 18.2 sec"
For the new best lap it will be just like "New Best lap: 15.8 sec"

**Comment by highway11** [comment]
I agree this is a great idea. It  is a very beneficial feature to hear your lap times called out as you are flying with the goggles on!

Another open source lap timer I built does this. It runs in the web browser though, and I much prefer the Android app interface you have built for this one.

**Comment by voroshkov** [comment]
https://github.com/voroshkov/Chorus-RF-Laptimer/pull/10
