### ISSUE TITLE
[request] - Manual RSSI input

### ISSUE THREAD

**Issue by jRreis** [voroshkov/Chorus-RF-Laptimer#40]
Request for manual RSSI input in Text format in android APP.

RSSI can only be Set/Clear and Increased or decreased by the value of 1, every time +/- is pressed. 

It would be a plus to allow RSSI values to be directly inserted, as text format, for manually set the value. 
E.g.. if we want to set manually an RSSI of 243, "+" must be pressed until that values is reached.  In text, we would be able to directly input the value "243".

**Comment by FranzAr** [comment]
+1
Great idea, maybe RSSI value could be stored, as you don't really have to change it a lot for different quads.

**Comment by rcdesigns** [comment]
Yes, just storing the last RSSI value would be great.  I find I'm always using around 200 and don't need to calibrate every time.

**Comment by kestux75** [comment]
+1 for storing the last RSSI

**Comment by voroshkov** [comment]
done in release 0.6.1: https://github.com/voroshkov/Chorus-RF-Laptimer/tree/0.6.1
