### ISSUE TITLE
Support Connex Prosight fixed channels

### ISSUE THREAD

**Issue by ps915** [voroshkov/Chorus-RF-Laptimer#44]
Why not implementing the fixed channels?

https://connexuav.zendesk.com/hc/en-us/articles/211648026-Frequency-Management

![image](https://user-images.githubusercontent.com/3420935/28232986-f89de2aa-68f3-11e7-8c85-d685c4db3063.png)
![image](https://user-images.githubusercontent.com/3420935/28233091-b3e8f0f4-68f4-11e7-845f-22eaa463d6ed.png)

**Comment by voroshkov** [comment]
Does it mean they have different channels set for different countries?

**Comment by anunique** [comment]
guess this one is done and can be closed ;]

**Comment by voroshkov** [comment]
done by @anunique ;)
