### ISSUE TITLE
I can't connect with Windows GUI

### ISSUE THREAD

**Issue by MoonKIE666** [voroshkov/Chorus-RF-Laptimer#54]
Hello everyone,

I can not connect to the Windows application.

I connect my CHORUS 5 in 1 through a FTDI to my pc, I open the windows GUI and I get the startup window, but I only get the baud rate dropdown, I put it in 11520 and the COM port dropdown does not appear .

What's going on? My FTDI works correctly, I installed the firmware on all my mini arduino with it. And in the Windows Device Manager I appears as connected on the COM3 port.

Let's see if someone can help me.

I've also tried connecting it to GOOGLE CHROME's EASYRACELAPTIMER app, but it will not let me.

**Comment by anunique** [comment]
you might want to post problems like that @ https://github.com/anunique/ChorusGUI

guess this one can be marked as solved since its not a problem with the chorus-rf-laptimer project at all ;]
