### ISSUE TITLE
Different Modes for the Android app

### ISSUE THREAD

**Issue by ty8447** [voroshkov/Chorus-RF-Laptimer#56]
Hello, I have been using the Android app a lot and love it, but I was wondering if there was a modded version of the app that includes a point mode where there is a countdown timer and during that set time, people race to get the most amount of laps. When the time is over people can finish their lap and then they are done. This is similar to how normal multigp races are scored.

**Comment by highway11** [comment]
I've added this feature to my branch. It's fairly crudely implemented but you can do a timed race for 1.5, 2, or 2.5 minutes. It announces time remaining at certain intervals as well as when the time is up

**Comment by ty8447** [comment]
@highway11 How would I set that up? Would I have to upload new code to the pro mini and/or download a modded version of the Android app?

**Comment by highway11** [comment]
You would just need the app. There is no code I have changed for the Arduinos
