### ISSUE TITLE
Ability to Manually Type RSSI Threshold

### ISSUE THREAD

**Issue by ty8447** [voroshkov/Chorus-RF-Laptimer#62]
Can there be an added feature in the near future to click on the RSSI value and type in a number, rather than only being able to press the buttons?

**Comment by anunique** [comment]
check https://github.com/voroshkov/Chorus-RF-Laptimer/issues/40

the arduino code supports setting the rssi threshold, somebody just needs to add it to the android app ;]

**Comment by voroshkov** [comment]
sorry guys, I won't add.
long button clicks changes by 30. 
10 long clicks is enough to cover all range
