### ISSUE TITLE
First Pilot/Device only reads 1018 for the RSSI level no matter what

### ISSUE THREAD

**Issue by ty8447** [voroshkov/Chorus-RF-Laptimer#63]
I have two lap timers and when they connect with the phone, the lap timer with the Stepdown (Timer 1/ Pilot 1) does not give an accurate RSSI level. The second lap timer on the other hand, does work in the app and pc version. All of the wiring is the exact same on both devices and in the diagram, and I have tried everything in the troubleshooting section.

**Comment by voroshkov** [comment]
please describe the sympthoms

**Comment by ty8447** [comment]
When I open the app and have two Solo's connected, the second solo will give an accurate reading of the rssi value and the first solo that has the 5v step down displays 1018 for it's value regardless of Band/Channel. When you start the race, as you mentioned in another issue that they will go to zero to help with communication and that happens for both (so the software is controlling that).

**Comment by voroshkov** [comment]
Maybe you have bad (or not patched) vrx.
Try measuring actual voltage on its RSSI pin - it should be around 0.5 - 1.5 V

**Comment by ty8447** [comment]
If I use a multimeter to measure the rssi pin on the rx5808 using the positive lead for the rssi and ground being anywhere else (preferably the 5v step down) I get a reading of about 5v.

**Comment by voroshkov** [comment]
that's wrong RSSI. probably your RX5808 is damaged
