### ISSUE TITLE
Improvment: Link up to 3 receiver per arduino

### ISSUE THREAD

**Issue by elvince** [voroshkov/Chorus-RF-Laptimer#66]
Hi,

First thanks for sharing this, it is really great.

Why didn't you link more receiver per Arduino? I think you can put up to 3 per arduino. 
Was it because the loop will take more than 1ms?

If not, it might be an improvment that allow to have cheaper kit for 3 drones (which is great for friend racing!)

Thanks!

**Comment by voroshkov** [comment]
Because of modular design. 
Suggested improvement is out of scope of this project.
