### ISSUE TITLE
Documentations

### ISSUE THREAD

**Issue by CorentinPacaud** [voroshkov/Chorus-RF-Laptimer#69]
https://github.com/voroshkov/Chorus-RF-Laptimer/blob/1e01318f48f0c909f864a3713422c2f551f02a34/Arduino/chorus-rf-laptimer/rx5808spi.h#L82

Hi,
this is not an issue but a question about documentation.
In the code quoted (5lines), why did you do that ?
How did you know you have to do this transformation of data ?

Thx

**Comment by voroshkov** [comment]
1. This code was contributed by @anunique.
2. There's an algorithm in rx5808 datasheet.
