### ISSUE TITLE
[Feature request] Low voltage Alarm

### ISSUE THREAD

**Issue by voroshkov** [voroshkov/Chorus-RF-Laptimer#7]
It would be nice to have a low voltage alarm in the application if Chorus device is powered from accumulator.

**Comment by traced** [comment]
Dont know if that would be useful, mostly it will be powered by a 5v stepdown. You would need another voltage divider "in front" to get the voltage in front of the stepdown.

**Comment by voroshkov** [comment]
Right. That's not a priority, but nice to have.
