### ISSUE TITLE
COM connection Android app

### ISSUE THREAD

**Issue by Snap1202** [voroshkov/Chorus-RF-Laptimer#72]
is it possible to add com connection to the android app? I would like to use a 3dr Radio 433mhz as link to the unit as the bluetooth connection isnt working reliable for me. But Android app only shows WIFI or Bluetooth as option.

**Comment by voroshkov** [comment]
I'd definitely work on this, but don't have an Android phone with OTG support yet.

**Comment by voroshkov** [comment]
Duplicate of #43
