### ISSUE TITLE
CSV Report to xls table

### ISSUE THREAD

**Issue by JLOFPV** [voroshkov/Chorus-RF-Laptimer#78]
I would like to know if there is a possibility to make the format in which the reports are saved could be an excel table organized in columns. Thank you.

**Comment by voroshkov** [comment]
CSV is easily open in Excel as you need.

**Comment by JLOFPV** [comment]
I was referring to that it appeared ordered in excel tables, but I have seen that the conversion can be made from the same excel. Thank you. ;)
