### ISSUE TITLE
New logo proposal for Chorus RF Laptimer app

### ISSUE THREAD

**Issue by ammarraisafti** [voroshkov/Chorus-RF-Laptimer#94]
Hi admin, I would like to offer a simple new logo design for Chorus RF Laptimer app. This logo is my special design for you. If you are willing to accept it, you simply reply to this proposal. I will send you a new logo of this file. And if you want another color variation or some additional icon in it. You can tell me. I will update it soon. thank you

![fr](https://user-images.githubusercontent.com/37721970/41307977-dc72499c-6ea4-11e8-92ec-480f98e3afd7.png)

**Comment by voroshkov** [comment]
Thanks for the proposal, but I don't think it needs rebranding yet :)
