### ISSUE TITLE
Would it be possible to use Esp32 or ESP8266 as the main MCU?

### ISSUE THREAD

**Issue by JesusGonfer** [voroshkov/Chorus-RF-Laptimer#98]
It would be possible to use one of these devices to replace the arduino. With this we would get wifi / bluetooth in a simpler way

**Comment by voroshkov** [comment]
There's a project with ESP32 already. Check recent posts in the Facebook group.

**Comment by JesusGonfer** [comment]
thank you very much I can help you in that!
